version: "3.7"

networks:
  docker-practice-net:
    driver:
      bridge

services:
  db:
    image: postgres:11
    networks: 
    - docker-practice-net
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
    volumes: 
    - "../../data/postgres:/data/postgres"
    - "../../data/dump:/db-dump"
    ports:
    - "127.0.0.1:5432:5432"
  redis:
    image: redis
    networks: 
    - docker-practice-net
    ports:
    - "6379:6379"
